export const INDIAN_STATES = [
  'National',
  'Karnataka',
  'Maharashtra',
  'Tamil Nadu',
  'Telangana',
  'Kerala',
  'Delhi',
  'Gujarat',
  'Andhra Pradesh',
  'Uttar Pradesh',
  'West Bengal',
  'Bihar',
  'Haryana',
  'Punjab',
  'Rajasthan',
  'Madhya Pradesh',
];

export const STATE_CITIES = {
  Karnataka: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubli'],
  Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Nashik'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai'],
  Telangana: ['Hyderabad', 'Warangal'],
  Kerala: ['Kochi', 'Thiruvananthapuram', 'Kozhikode'],
  Delhi: ['New Delhi', 'Delhi'],
  Gujarat: ['Ahmedabad', 'Surat', 'Vadodara'],
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada'],
  'Uttar Pradesh': ['Lucknow', 'Noida', 'Kanpur'],
  'West Bengal': ['Kolkata', 'Howrah'],
  Bihar: ['Patna', 'Gaya'],
  Haryana: ['Gurugram', 'Faridabad'],
  Punjab: ['Ludhiana', 'Amritsar'],
  Rajasthan: ['Jaipur', 'Jodhpur'],
  'Madhya Pradesh': ['Indore', 'Bhopal'],
};
